# Generated by Django 6.0.2 on 2026-02-26 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        ("transactons", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowrecord",
            name="book",
        ),
        migrations.RemoveField(
            model_name="borrowrecord",
            name="returned",
        ),
        migrations.CreateModel(
            name="BorrowRecordItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("returned", models.BooleanField(default=False)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "borrow_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="transactons.borrowrecord",
                    ),
                ),
            ],
        ),
    ]
